name: Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Cookiecutter
        run:  pip install --user cookiecutter

      - name: Generate sample project
        run: ~/.local/bin/cookiecutter --no-input .

      - name: Test with pytest
        run: |
          cd pyramidapi
          docker-compose -f test-compose.yml up --exit-code-from pyramidapi-test pyramidapi-test

      - name: Upload coverage report
        env:
          CODECOV_BINARY_URL: https://uploader.codecov.io/latest/linux/codecov
          CODECOV_SHASUM_URL: https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
          CODECOV_SHASUM_SIGNATURE_URL: https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
          CODECOV_PGP_KEY_URL: https://keybase.io/codecovsecurity/pgp_keys.asc
        run: |
          curl -s $CODECOV_BINARY_URL > codecov
          chmod +x codecov
          curl $CODECOV_PGP_KEY_URL | gpg --import
          curl -Os $CODECOV_SHASUM_URL
          curl -Os $CODECOV_SHASUM_SIGNATURE_URL
          gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM  \
            && sha256sum --check codecov.SHA256SUM \
            && ./codecov
